In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
# 讀取 app_train
app_train = pd.read_csv('application_train.csv')

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [64]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head()

(307511, 1)


WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [65]:
sub_train['WEEKDAY_APPR_PROCESS_START'].unique()

array(['WEDNESDAY', 'MONDAY', 'THURSDAY', 'SUNDAY', 'SATURDAY', 'FRIDAY',
       'TUESDAY'], dtype=object)

In [66]:
sub_train['WEEKDAY_APPR_PROCESS_START'].unique().shape

(7,)

In [72]:
"""
Your Code Here
"""
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
# 先將object轉成數值型態
label_encoder = LabelEncoder()
sub_train['WEEKDAY_APPR_PROCESS_START'] = label_encoder.fit_transform(sub_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train[0:5])
type(sub_train['WEEKDAY_APPR_PROCESS_START'])

   WEEKDAY_APPR_PROCESS_START
0                           6
1                           1
2                           1
3                           6
4                           4


pandas.core.series.Series

In [74]:
# 再將數值型態轉成binary code
onehot_encoder = OneHotEncoder(sparse = False)
code = np.array(sub_train['WEEKDAY_APPR_PROCESS_START'])
code =code.reshape(len(code),1)
onehot_encoded = onehot_encoder.fit_transform(code)
print(onehot_encoded[0:5])

[[0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]]


In [75]:
onehot_encoded = pd.DataFrame(onehot_encoded)

In [76]:
print(onehot_encoded.shape)
print(onehot_encoded.head())

(307511, 7)
     0    1    2    3    4    5    6
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  1.0
4  0.0  0.0  0.0  0.0  1.0  0.0  0.0
